package com.example.manana.apilol;

import java.util.Map;

/**
 * Created by Trabajo on 24/06/2016.
 */
public class DatosEstaticos {

    //Estos datos deberían estar en un SharedPreferences o incluso en una bbdd SQLite.
    //Los pongo de esta manera provisionalmente  por falta de tiempo.

    public Map<Integer, String> devolverMapaPersonajes(Map<Integer, String> mapaPersonajes)
    {
        mapaPersonajes.put(35,"Shaco");
        mapaPersonajes.put(36,"DrMundo");
        mapaPersonajes.put(33,"Rammus");
        mapaPersonajes.put(34,"Anivia");
        mapaPersonajes.put(39,"Irelia");
        mapaPersonajes.put(157,"Yasuo");
        mapaPersonajes.put(37,"Sona");
        mapaPersonajes.put(38,"Kassadin");
        mapaPersonajes.put(154,"Zac");
        mapaPersonajes.put(150,"Gnar");
        mapaPersonajes.put(43,"Karma");
        mapaPersonajes.put(42,"Corki");
        mapaPersonajes.put(41,"Gangplank");
        mapaPersonajes.put(40,"Janna");
        mapaPersonajes.put(202,"Jhin");
        mapaPersonajes.put(203,"Kindred");
        mapaPersonajes.put(201,"Braum");
        mapaPersonajes.put(22,"ashe");
        mapaPersonajes.put(23,"Tryndamere");
        mapaPersonajes.put(24,"Jax");
        mapaPersonajes.put(25,"Morgana");
        mapaPersonajes.put(26,"Zilean");
        mapaPersonajes.put(27,"Singed");
        mapaPersonajes.put(28,"Evelynn");
        mapaPersonajes.put(29,"Twitch");
        mapaPersonajes.put(3,"Galio");
        mapaPersonajes.put(161,"Velkoz");
        mapaPersonajes.put(2,"Olaf");
        mapaPersonajes.put(1,"Annie");
        mapaPersonajes.put(163,"Taliyah");
        mapaPersonajes.put(30,"Karthus");
        mapaPersonajes.put(7,"Leblanc");
        mapaPersonajes.put(6,"Urgot");
        mapaPersonajes.put(32,"Amumu");
        mapaPersonajes.put(5,"XinZhao");
        mapaPersonajes.put(31,"Chogath");
        mapaPersonajes.put(4,"TwistedFate");
        mapaPersonajes.put(9,"FiddleSticks");
        mapaPersonajes.put(8,"Vladimir");
        mapaPersonajes.put(19,"Warwick");
        mapaPersonajes.put(17,"Teemo");
        mapaPersonajes.put(18,"Tristana");
        mapaPersonajes.put(15,"Sivir");
        mapaPersonajes.put(16,"Soraka");
        mapaPersonajes.put(13,"Ryze");
        mapaPersonajes.put(14,"Sion");
        mapaPersonajes.put(11,"MasterYi");
        mapaPersonajes.put(12,"Alistar");
        mapaPersonajes.put(21,"MissFortune");
        mapaPersonajes.put(20,"Nunu");
        mapaPersonajes.put(107,"Rengar");
        mapaPersonajes.put(106,"Volibear");
        mapaPersonajes.put(105,"Fizz");
        mapaPersonajes.put(104,"Graves");
        mapaPersonajes.put(103,"Ahri");
        mapaPersonajes.put(102,"Shyvana");
        mapaPersonajes.put(99,"Lux");
        mapaPersonajes.put(101,"Xerath");
        mapaPersonajes.put(412,"Thresh");
        mapaPersonajes.put(98,"Shen");
        mapaPersonajes.put(96,"KogMaw");
        mapaPersonajes.put(222,"Jinx");
        mapaPersonajes.put(223,"TahmKench");
        mapaPersonajes.put(92,"Riven");
        mapaPersonajes.put(91,"Talon");
        mapaPersonajes.put(90,"Malzahar");
        mapaPersonajes.put(10,"Kayle");
        mapaPersonajes.put(429,"Kalista");
        mapaPersonajes.put(421,"RekSai");
        mapaPersonajes.put(420,"Illaoi");
        mapaPersonajes.put(89,"Leona");
        mapaPersonajes.put(117,"Lulu");
        mapaPersonajes.put(79,"Gragas");
        mapaPersonajes.put(78,"Poppy");
        mapaPersonajes.put(114,"Fiora");
        mapaPersonajes.put(115,"Ziggs");
        mapaPersonajes.put(77,"Udyr");
        mapaPersonajes.put(112,"Viktor");
        mapaPersonajes.put(113,"Sejuani");
        mapaPersonajes.put(110,"Varus");
        mapaPersonajes.put(111,"Nautilus");
        mapaPersonajes.put(119,"Draven");
        mapaPersonajes.put(432,"Bard");
        mapaPersonajes.put(82,"Mordekaiser");
        mapaPersonajes.put(245,"Ekko");
        mapaPersonajes.put(83,"Yorik");
        mapaPersonajes.put(80,"Pantheon");
        mapaPersonajes.put(81,"Ezreal");
        mapaPersonajes.put(86,"Garen");
        mapaPersonajes.put(84,"Akali");
        mapaPersonajes.put(85,"Kennen");
        mapaPersonajes.put(67,"Vayne");
        mapaPersonajes.put(126,"Jayce");
        mapaPersonajes.put(127,"Lissandra");
        mapaPersonajes.put(69,"Cassiopeia");
        mapaPersonajes.put(68,"Rumble");
        mapaPersonajes.put(121,"Khazix");
        mapaPersonajes.put(122,"Darius");
        mapaPersonajes.put(120,"Hecarim");
        mapaPersonajes.put(72,"Skarner");
        mapaPersonajes.put(236,"Lucian");
        mapaPersonajes.put(74,"Heimerdinger");
        mapaPersonajes.put(75,"Nasus");
        mapaPersonajes.put(238,"Zed");
        mapaPersonajes.put(76,"Nidalee");
        mapaPersonajes.put(134,"Syndra");
        mapaPersonajes.put(59,"JarvanIV");
        mapaPersonajes.put(133,"Quinn");
        mapaPersonajes.put(58,"Renekton");
        mapaPersonajes.put(57,"Maokai");
        mapaPersonajes.put(136,"AurelionSol");
        mapaPersonajes.put(56,"Nocturne");
        mapaPersonajes.put(55,"Katarina");
        mapaPersonajes.put(64,"LeeSin");
        mapaPersonajes.put(62,"MonkeyKing");
        mapaPersonajes.put(268,"Azir");
        mapaPersonajes.put(63,"Brand");
        mapaPersonajes.put(131,"Diana");
        mapaPersonajes.put(60,"Elise");
        mapaPersonajes.put(267,"Nami");
        mapaPersonajes.put(266,"Aatrox");
        mapaPersonajes.put(61,"Orianna");
        mapaPersonajes.put(143,"Zyra");
        mapaPersonajes.put(48,"Trundle");
        mapaPersonajes.put(45,"Veigar");
        mapaPersonajes.put(44,"Taric");
        mapaPersonajes.put(51,"Caitlyn");
        mapaPersonajes.put(53,"Blitzcrank");
        mapaPersonajes.put(54,"Malphite");
        mapaPersonajes.put(254,"Vi");
        mapaPersonajes.put(50,"Swain");
        return mapaPersonajes;
    }
}
